### ISSUE TITLE
Authorization error 401 in Gitpod

### ISSUE THREAD

**Issue by lahcenbcf** [CorpoSense/talent-campus-lms#2]
The 401 Unauthorized error typically indicates that your server is refusing to process the request because it lacks valid authentication credentials. When this happens in a development environment inGitpod

**Comment by bitsnaps** [comment]
There are some potential cause for this issue, let's tackle them one by one:
1- We'll make sure this has nothing to do with being this repo private -> I've turned the visibility to public now, so we can freely open it in gitpod (private repo are allowed only for limited time with the free account).
2- Use the following command to test endpoints: `curl http://0.0.0.0:8000/lms/` instead of the subdomain.
3- In case this issue is related to [Gitpod](https://github.com/gitpod-io/gitpod/issues/14576), try to take a look at the their issues.

Please provide more details (screenshot, commits...), or push the error so I can dig more deeper.

Check the current PRs, then let me know if that works now.
